import path from "node:path";
import fsp from "node:fs/promises";
import { config } from "@/lib/config";
import { createStoryProject, getAutoStorySettings, setAutoStorySettings, getUnusedIdea, addIdeasToPool, markIdeaPoolUsed, countUnusedIdeas, type StoryIdea } from "@/lib/database";
import { generateIdeaBatch, generateOriginalStoryFromPremise } from "@/services/story/generator";
import { runStoryGenerationPipeline } from "@/services/story/pipeline";

export type StoryChannel = "story" | "english";

const POOL_REFILL_THRESHOLD = 5;
const POOL_REFILL_SIZE = 20;

/** Draws one fresh premise from the local idea pool, refilling it from Gemini
 * first if it's running low. No external scraping at all — Reddit's public API
 * is blocked (403) and their official API's "Responsible Builder Policy"
 * restricts this exact AI-content-generation use case, so premises are
 * self-generated by Gemini instead (see generateIdeaBatch). */
async function fetchFreshIdea(): Promise<StoryIdea | undefined> {
  if (countUnusedIdeas() < POOL_REFILL_THRESHOLD) {
    const batch = await generateIdeaBatch(POOL_REFILL_SIZE);
    if (batch.length > 0) addIdeasToPool(batch);
  }
  return getUnusedIdea();
}

export { getAutoStorySettings, setAutoStorySettings };

type PreparedIdea = { projectId: number; premise: string; pipelineParams: Parameters<typeof runStoryGenerationPipeline>[1] };

/** The FAST half of an automated run: pick a fresh premise, have Gemini write a
 * wholly original story from it, and create the project row. Kept separate
 * from the slow render half so idea-availability/Gemini errors surface
 * immediately to a caller awaiting this — e.g. the manual-trigger API route —
 * instead of being lost inside a fire-and-forget background job. Throws on failure. */
async function prepareAutoStoryIdea(channel: StoryChannel): Promise<PreparedIdea | null> {
  const language = channel === "english" ? "en" : "ta";
  const idea = await fetchFreshIdea();
  if (!idea) return null;

  const durationSeconds = 180;
  const voice = "Female — Warm";
  const story = await generateOriginalStoryFromPremise(idea.premise, language);

  const projectId = createStoryProject(story, durationSeconds, voice, {
    aspectRatio: "16:9",
    bgm: true,
    animate: true,
    language,
    mediaSource: "stock",
    ttsMode: "free",
    localize: false,
    intendedChannel: channel,
  });
  markIdeaPoolUsed(idea.id);

  const mediaDir = path.join(config.mediaRoot, "story", String(projectId));
  await fsp.mkdir(mediaDir, { recursive: true });

  return {
    projectId,
    premise: idea.premise,
    pipelineParams: { story, durationSeconds, voice, aspectRatio: "16:9", language, ttsMode: "free", localize: false, mediaDir },
  };
}

/** Full automated run, used by the scheduler (awaited end-to-end so heavy runs
 * stay serialized): pick a fresh premise → Gemini writes a wholly original
 * story → feeds the same render pipeline the manual create form uses. Renders
 * only — does NOT auto-upload (kept for manual review, per the earlier
 * real-publish incident lesson); the dashboard's channel page shows it once done. */
export async function runAutoStoryPipeline(channel: StoryChannel): Promise<{ projectId: number; premise: string } | { skipped: string }> {
  const prepared = await prepareAutoStoryIdea(channel);
  if (!prepared) return { skipped: "Idea pool காலியாக உள்ளது, Gemini-கிட்டயும் புதிய idea கிடைக்கவில்லை" };
  await runStoryGenerationPipeline(prepared.projectId, prepared.pipelineParams);
  return { projectId: prepared.projectId, premise: prepared.premise };
}

/** Manual-trigger version: awaits only the fast idea-prep half (so errors
 * return immediately to the HTTP caller), then lets the slow render run in the
 * background — same fire-and-forget convention as the manual create route. */
export async function triggerAutoStoryOnce(channel: StoryChannel): Promise<{ projectId: number; premise: string } | { skipped: string }> {
  const prepared = await prepareAutoStoryIdea(channel);
  if (!prepared) return { skipped: "Idea pool காலியாக உள்ளது, Gemini-கிட்டயும் புதிய idea கிடைக்கவில்லை" };
  runStoryGenerationPipeline(prepared.projectId, prepared.pipelineParams);
  return { projectId: prepared.projectId, premise: prepared.premise };
}
